version: 1
default_environment: dev
project_id: 6227d599-2581-4f8f-8174-567c63a192e8
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
  - name: tap-postgres-source
    inherit_from: tap-postgres
    config:
      host: host.docker.internal
      port: 5432
      user: northwind_user
      database: northwind
      filter_schemas:
      - public
    select:
    - '*.*'
    - '!public-products.unit_price'
    - '!public-orders.freight'
  - name: tap-postgres-destination
    inherit_from: tap-postgres
    config:
      database: data_destination
      host: host.docker.internal
      port: 5433
      user: admin
      filter_schemas:
      - analysis
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
  - name: tap-csv-source
    inherit_from: tap-csv
    config:
      files:
      - entity: order_details
        path: input
        keys: []
    select:
    - order_details.*
  - name: tap-csv-local-disk
    inherit_from: tap-csv
    config:
      csv_files_definition: data/.temp/files_definition.json
    select:
    - '*.*'
  loaders:
  - name: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
      file_naming_scheme: '{stream_name}.csv'
  - name: target-csv-local-disk-from-csv
    inherit_from: target-csv
    config:
      destination_path: data/.temp/csv
  - name: target-csv-local-disk-from-postgres
    inherit_from: target-csv
    config:
      destination_path: data/.temp/postgres
  - name: target-postgres
    variant: meltanolabs
    pip_url: meltanolabs-target-postgres
    config:
      database: data_destination
      host: host.docker.internal
      port: 5433
      user: admin
      default_target_schema: raw
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
    config:
      destination_path: data/result
      do_timestamp_file: true
  orchestrators:
  - name: airflow
    variant: apache
    pip_url: apache-airflow==2.1.2 --constraint 
      https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt
  files:
  - name: files-airflow
    variant: meltano
    pip_url: git+https://github.com/meltano/files-airflow.git
  utilities:
  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.8.1
      --constraint 
      https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
  - name: data_process
    namespace: data_process
    commands:
      organize_csv_files:
        args: py/organize_csv_files.py data
        executable: python
      generate_files_definition:
        args: py/generate_files_definition.py data
        executable: python
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core dbt-postgres<1.8 git+https://github.com/meltano/dbt-ext.git@main
    config:
      dbname: data_destination
      host: host.docker.internal
      port: 5433
      schema: analysis
      user: admin
      skip_pre_invoke: true
jobs:
- name: input-to-local-disk
  tasks:
  - tap-postgres-source target-csv-local-disk-from-postgres
  - tap-csv-source target-csv-local-disk-from-csv
  - data_process:organize_csv_files
- name: local-disk-to-destination
  tasks:
  - data_process:generate_files_definition
  - tap-csv-local-disk target-postgres
  - dbt-postgres:run
  - tap-postgres-destination target-jsonl
schedules:
- name: input-to-local-disk-daily
  interval: '* * * * *'
  job: input-to-local-disk
- name: local-disk-to-destination-daily
  interval: '* * * * *'
  job: local-disk-to-destination
